language: node_js
node_js:
  - '12'
install:
  - npm install -g codecov
script:
  - yarn install
  - yarn lint
  - yarn test:coverage --runInBand --no-cache
  - npm run test
  - codecov
cache:
  directories:
    - node_modules